// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"strings"
)

const createStoreFile = `-- name: CreateStoreFile :one
INSERT INTO StoreFile (store_path_id, path, size, type, link_target, executable, hash)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, store_path_id, path, size, type, link_target, executable, hash
`

type CreateStoreFileParams struct {
	StorePathID int64
	Path        string
	Size        int64
	Type        int64
	LinkTarget  sql.NullString
	Executable  bool
	Hash        []byte
}

func (q *Queries) CreateStoreFile(ctx context.Context, arg CreateStoreFileParams) (Storefile, error) {
	row := q.db.QueryRowContext(ctx, createStoreFile,
		arg.StorePathID,
		arg.Path,
		arg.Size,
		arg.Type,
		arg.LinkTarget,
		arg.Executable,
		arg.Hash,
	)
	var i Storefile
	err := row.Scan(
		&i.ID,
		&i.StorePathID,
		&i.Path,
		&i.Size,
		&i.Type,
		&i.LinkTarget,
		&i.Executable,
		&i.Hash,
	)
	return i, err
}

const createStorePath = `-- name: CreateStorePath :one
INSERT INTO StorePath (path) VALUES (?) RETURNING id, path
`

func (q *Queries) CreateStorePath(ctx context.Context, path string) (Storepath, error) {
	row := q.db.QueryRowContext(ctx, createStorePath, path)
	var i Storepath
	err := row.Scan(&i.ID, &i.Path)
	return i, err
}

const getLocalFileByHash = `-- name: GetLocalFileByHash :one
SELECT file.id, file.store_path_id, file.path, file.size, file.type, file.link_target, file.executable, file.hash FROM StoreFile file
JOIN StorePath path ON path.id = file.store_path_id
WHERE file.hash = ? AND path.path IN (/*SLICE:local_paths*/?)
LIMIT 1
`

type GetLocalFileByHashParams struct {
	Hash       []byte
	LocalPaths []string
}

// A store file the target already has (on one of local_paths) with the given
// content hash, for whole-file and directory matching.
func (q *Queries) GetLocalFileByHash(ctx context.Context, arg GetLocalFileByHashParams) (Storefile, error) {
	query := getLocalFileByHash
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Hash)
	if len(arg.LocalPaths) > 0 {
		for _, v := range arg.LocalPaths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:local_paths*/?", strings.Repeat(",?", len(arg.LocalPaths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:local_paths*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var i Storefile
	err := row.Scan(
		&i.ID,
		&i.StorePathID,
		&i.Path,
		&i.Size,
		&i.Type,
		&i.LinkTarget,
		&i.Executable,
		&i.Hash,
	)
	return i, err
}

const getStoreChunksWithLocalMatch = `-- name: GetStoreChunksWithLocalMatch :many
SELECT
  nc.size, nc.offset, nc.hash,
  COALESCE(lc.file_id, 0) AS local_file_id,
  COALESCE(lc.size, 0) AS local_size,
  COALESCE(lc.offset, 0) AS local_offset
FROM Chunk nc
LEFT JOIN Chunk lc
  ON lc.hash = nc.hash
  AND lc.file_id IN (
    SELECT file.id FROM StoreFile file
    JOIN StorePath path ON path.id = file.store_path_id
    WHERE path.path IN (/*SLICE:local_paths*/?)
  )
WHERE nc.file_id = ?
GROUP BY nc.id
ORDER BY nc.id
`

type GetStoreChunksWithLocalMatchParams struct {
	LocalPaths []string
	FileID     int64
}

type GetStoreChunksWithLocalMatchRow struct {
	Size        int64
	Offset      int64
	Hash        []byte
	LocalFileID int64
	LocalSize   int64
	LocalOffset int64
}

// Each chunk of file_id (in order), joined to a chunk the target already has
// (on one of local_paths) with the same content. local_file_id is 0 when the
// target does not have the chunk. GROUP BY collapses a hash present in several
// local files to a single match.
func (q *Queries) GetStoreChunksWithLocalMatch(ctx context.Context, arg GetStoreChunksWithLocalMatchParams) ([]GetStoreChunksWithLocalMatchRow, error) {
	query := getStoreChunksWithLocalMatch
	var queryParams []interface{}
	if len(arg.LocalPaths) > 0 {
		for _, v := range arg.LocalPaths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:local_paths*/?", strings.Repeat(",?", len(arg.LocalPaths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:local_paths*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.FileID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoreChunksWithLocalMatchRow
	for rows.Next() {
		var i GetStoreChunksWithLocalMatchRow
		if err := rows.Scan(
			&i.Size,
			&i.Offset,
			&i.Hash,
			&i.LocalFileID,
			&i.LocalSize,
			&i.LocalOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreFileByID = `-- name: GetStoreFileByID :one
SELECT id, store_path_id, path, size, type, link_target, executable, hash FROM StoreFile WHERE id = ?
`

func (q *Queries) GetStoreFileByID(ctx context.Context, id int64) (Storefile, error) {
	row := q.db.QueryRowContext(ctx, getStoreFileByID, id)
	var i Storefile
	err := row.Scan(
		&i.ID,
		&i.StorePathID,
		&i.Path,
		&i.Size,
		&i.Type,
		&i.LinkTarget,
		&i.Executable,
		&i.Hash,
	)
	return i, err
}

const getStoreFiles = `-- name: GetStoreFiles :many
SELECT file.id, file.store_path_id, file.path, file.size, file.type, file.link_target, file.executable, file.hash FROM StoreFile AS file JOIN StorePath path ON path.id = file.store_path_id WHERE path.path = ? ORDER BY file.id
`

func (q *Queries) GetStoreFiles(ctx context.Context, path string) ([]Storefile, error) {
	rows, err := q.db.QueryContext(ctx, getStoreFiles, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Storefile
	for rows.Next() {
		var i Storefile
		if err := rows.Scan(
			&i.ID,
			&i.StorePathID,
			&i.Path,
			&i.Size,
			&i.Type,
			&i.LinkTarget,
			&i.Executable,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorePath = `-- name: GetStorePath :one
SELECT id, path FROM StorePath WHERE path = ?
`

func (q *Queries) GetStorePath(ctx context.Context, path string) (Storepath, error) {
	row := q.db.QueryRowContext(ctx, getStorePath, path)
	var i Storepath
	err := row.Scan(&i.ID, &i.Path)
	return i, err
}

const getStorePathByID = `-- name: GetStorePathByID :one
SELECT id, path FROM StorePath WHERE id = ?
`

func (q *Queries) GetStorePathByID(ctx context.Context, id int64) (Storepath, error) {
	row := q.db.QueryRowContext(ctx, getStorePathByID, id)
	var i Storepath
	err := row.Scan(&i.ID, &i.Path)
	return i, err
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO Chunk (file_id, hash, size, offset)
VALUES (?, ?, ?, ?)
`

type InsertChunkParams struct {
	FileID int64
	Hash   []byte
	Size   int64
	Offset int64
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.db.ExecContext(ctx, insertChunk,
		arg.FileID,
		arg.Hash,
		arg.Size,
		arg.Offset,
	)
	return err
}
