// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: delta.proto

package delta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Delta reconstructs a target byte slice from a "base" (reference) file
type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*Delta_Op            `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_delta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_delta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_delta_proto_rawDescGZIP(), []int{0}
}

func (x *Delta) GetOps() []*Delta_Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

type Delta_Op struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Delta_Op_Copy
	//	*Delta_Op_Insert
	Op            isDelta_Op_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta_Op) Reset() {
	*x = Delta_Op{}
	mi := &file_delta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta_Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta_Op) ProtoMessage() {}

func (x *Delta_Op) ProtoReflect() protoreflect.Message {
	mi := &file_delta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta_Op.ProtoReflect.Descriptor instead.
func (*Delta_Op) Descriptor() ([]byte, []int) {
	return file_delta_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Delta_Op) GetOp() isDelta_Op_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Delta_Op) GetCopy() *Delta_Copy {
	if x != nil {
		if x, ok := x.Op.(*Delta_Op_Copy); ok {
			return x.Copy
		}
	}
	return nil
}

func (x *Delta_Op) GetInsert() []byte {
	if x != nil {
		if x, ok := x.Op.(*Delta_Op_Insert); ok {
			return x.Insert
		}
	}
	return nil
}

type isDelta_Op_Op interface {
	isDelta_Op_Op()
}

type Delta_Op_Copy struct {
	Copy *Delta_Copy `protobuf:"bytes,1,opt,name=copy,proto3,oneof"` // Copy from bas
}

type Delta_Op_Insert struct {
	Insert []byte `protobuf:"bytes,2,opt,name=insert,proto3,oneof"` // Insert literal bytes
}

func (*Delta_Op_Copy) isDelta_Op_Op() {}

func (*Delta_Op_Insert) isDelta_Op_Op() {}

type Delta_Copy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta_Copy) Reset() {
	*x = Delta_Copy{}
	mi := &file_delta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta_Copy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta_Copy) ProtoMessage() {}

func (x *Delta_Copy) ProtoReflect() protoreflect.Message {
	mi := &file_delta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta_Copy.ProtoReflect.Descriptor instead.
func (*Delta_Copy) Descriptor() ([]byte, []int) {
	return file_delta_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Delta_Copy) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Delta_Copy) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_delta_proto protoreflect.FileDescriptor

const file_delta_proto_rawDesc = "" +
	"\n" +
	"\vdelta.proto\x12\x05delta\"\xb1\x01\n" +
	"\x05Delta\x12!\n" +
	"\x03ops\x18\x01 \x03(\v2\x0f.delta.Delta.OpR\x03ops\x1aM\n" +
	"\x02Op\x12'\n" +
	"\x04copy\x18\x01 \x01(\v2\x11.delta.Delta.CopyH\x00R\x04copy\x12\x18\n" +
	"\x06insert\x18\x02 \x01(\fH\x00R\x06insertB\x04\n" +
	"\x02op\x1a6\n" +
	"\x04Copy\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06lengthB/Z-github.com/adisbladis/deltanar/internal/deltab\x06proto3"

var (
	file_delta_proto_rawDescOnce sync.Once
	file_delta_proto_rawDescData []byte
)

func file_delta_proto_rawDescGZIP() []byte {
	file_delta_proto_rawDescOnce.Do(func() {
		file_delta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delta_proto_rawDesc), len(file_delta_proto_rawDesc)))
	})
	return file_delta_proto_rawDescData
}

var file_delta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_delta_proto_goTypes = []any{
	(*Delta)(nil),      // 0: delta.Delta
	(*Delta_Op)(nil),   // 1: delta.Delta.Op
	(*Delta_Copy)(nil), // 2: delta.Delta.Copy
}
var file_delta_proto_depIdxs = []int32{
	1, // 0: delta.Delta.ops:type_name -> delta.Delta.Op
	2, // 1: delta.Delta.Op.copy:type_name -> delta.Delta.Copy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_delta_proto_init() }
func file_delta_proto_init() {
	if File_delta_proto != nil {
		return
	}
	file_delta_proto_msgTypes[1].OneofWrappers = []any{
		(*Delta_Op_Copy)(nil),
		(*Delta_Op_Insert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delta_proto_rawDesc), len(file_delta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delta_proto_goTypes,
		DependencyIndexes: file_delta_proto_depIdxs,
		MessageInfos:      file_delta_proto_msgTypes,
	}.Build()
	File_delta_proto = out.File
	file_delta_proto_goTypes = nil
	file_delta_proto_depIdxs = nil
}
