// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Chunk struct {
	ID     int64
	FileID int64
	Hash   []byte
	Size   int64
	Offset int64
}

type Storefile struct {
	ID          int64
	StorePathID int64
	Path        string
	Size        int64
	Type        int64
	LinkTarget  sql.NullString
	Executable  bool
	Hash        []byte
}

type Storepath struct {
	ID   int64
	Path string
}
