// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"strings"
)

const createStoreFile = `-- name: CreateStoreFile :one
INSERT INTO StoreFile (store_path_id, path, size, type, link_target, executable, hash)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, store_path_id, path, size, type, link_target, executable, hash
`

type CreateStoreFileParams struct {
	StorePathID int64
	Path        string
	Size        int64
	Type        int64
	LinkTarget  sql.NullString
	Executable  bool
	Hash        []byte
}

func (q *Queries) CreateStoreFile(ctx context.Context, arg CreateStoreFileParams) (Storefile, error) {
	row := q.db.QueryRowContext(ctx, createStoreFile,
		arg.StorePathID,
		arg.Path,
		arg.Size,
		arg.Type,
		arg.LinkTarget,
		arg.Executable,
		arg.Hash,
	)
	var i Storefile
	err := row.Scan(
		&i.ID,
		&i.StorePathID,
		&i.Path,
		&i.Size,
		&i.Type,
		&i.LinkTarget,
		&i.Executable,
		&i.Hash,
	)
	return i, err
}

const createStorePath = `-- name: CreateStorePath :one
INSERT INTO StorePath (path) VALUES (?) RETURNING id, path
`

func (q *Queries) CreateStorePath(ctx context.Context, path string) (Storepath, error) {
	row := q.db.QueryRowContext(ctx, createStorePath, path)
	var i Storepath
	err := row.Scan(&i.ID, &i.Path)
	return i, err
}

const getStoreChunks = `-- name: GetStoreChunks :many
SELECT id, file_id, hash, size, "offset" FROM Chunk WHERE file_id = ? ORDER BY id
`

func (q *Queries) GetStoreChunks(ctx context.Context, fileID int64) ([]Chunk, error) {
	rows, err := q.db.QueryContext(ctx, getStoreChunks, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chunk
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Hash,
			&i.Size,
			&i.Offset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreChunksByPaths = `-- name: GetStoreChunksByPaths :many
SELECT chunk.id, chunk.file_id, chunk.hash, chunk.size, chunk."offset" FROM Chunk as chunk
JOIN StoreFile file ON chunk.file_id = file.id
JOIN StorePath path ON file.store_path_id = path.id
WHERE path.path IN (/*SLICE:paths*/?)
ORDER BY chunk.id
`

func (q *Queries) GetStoreChunksByPaths(ctx context.Context, paths []string) ([]Chunk, error) {
	query := getStoreChunksByPaths
	var queryParams []interface{}
	if len(paths) > 0 {
		for _, v := range paths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:paths*/?", strings.Repeat(",?", len(paths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:paths*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chunk
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Hash,
			&i.Size,
			&i.Offset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreFileByID = `-- name: GetStoreFileByID :one
SELECT id, store_path_id, path, size, type, link_target, executable, hash FROM StoreFile WHERE id = ?
`

func (q *Queries) GetStoreFileByID(ctx context.Context, id int64) (Storefile, error) {
	row := q.db.QueryRowContext(ctx, getStoreFileByID, id)
	var i Storefile
	err := row.Scan(
		&i.ID,
		&i.StorePathID,
		&i.Path,
		&i.Size,
		&i.Type,
		&i.LinkTarget,
		&i.Executable,
		&i.Hash,
	)
	return i, err
}

const getStoreFiles = `-- name: GetStoreFiles :many
SELECT file.id, file.store_path_id, file.path, file.size, file.type, file.link_target, file.executable, file.hash FROM StoreFile AS file JOIN StorePath path ON path.id = file.store_path_id WHERE path.path = ? ORDER BY file.id
`

func (q *Queries) GetStoreFiles(ctx context.Context, path string) ([]Storefile, error) {
	rows, err := q.db.QueryContext(ctx, getStoreFiles, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Storefile
	for rows.Next() {
		var i Storefile
		if err := rows.Scan(
			&i.ID,
			&i.StorePathID,
			&i.Path,
			&i.Size,
			&i.Type,
			&i.LinkTarget,
			&i.Executable,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorePath = `-- name: GetStorePath :one
SELECT id, path FROM StorePath WHERE path = ?
`

func (q *Queries) GetStorePath(ctx context.Context, path string) (Storepath, error) {
	row := q.db.QueryRowContext(ctx, getStorePath, path)
	var i Storepath
	err := row.Scan(&i.ID, &i.Path)
	return i, err
}

const getStorePathByID = `-- name: GetStorePathByID :one
SELECT id, path FROM StorePath WHERE id = ?
`

func (q *Queries) GetStorePathByID(ctx context.Context, id int64) (Storepath, error) {
	row := q.db.QueryRowContext(ctx, getStorePathByID, id)
	var i Storepath
	err := row.Scan(&i.ID, &i.Path)
	return i, err
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO Chunk (file_id, hash, size, offset)
VALUES (?, ?, ?, ?)
`

type InsertChunkParams struct {
	FileID int64
	Hash   []byte
	Size   int64
	Offset int64
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.db.ExecContext(ctx, insertChunk,
		arg.FileID,
		arg.Hash,
		arg.Size,
		arg.Offset,
	)
	return err
}
