// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: dnar.proto

package dnar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent before a stream of other messages indicating how many messages will follow
type StreamHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        uint64                 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHeader) Reset() {
	*x = StreamHeader{}
	mi := &file_dnar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHeader) ProtoMessage() {}

func (x *StreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHeader.ProtoReflect.Descriptor instead.
func (*StreamHeader) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{0}
}

func (x *StreamHeader) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// A file being used as an input to write another file
type FileDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorePath     uint32                 `protobuf:"varint,1,opt,name=store_path,json=storePath,proto3" json:"store_path,omitempty"` // Store path offset in DnarHeader.paths
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDescriptor) Reset() {
	*x = FileDescriptor{}
	mi := &file_dnar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDescriptor) ProtoMessage() {}

func (x *FileDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDescriptor.ProtoReflect.Descriptor instead.
func (*FileDescriptor) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{1}
}

func (x *FileDescriptor) GetStorePath() uint32 {
	if x != nil {
		return x.StorePath
	}
	return 0
}

func (x *FileDescriptor) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// A content addressed chunk
type CAChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAChunk) Reset() {
	*x = CAChunk{}
	mi := &file_dnar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAChunk) ProtoMessage() {}

func (x *CAChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAChunk.ProtoReflect.Descriptor instead.
func (*CAChunk) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{2}
}

func (x *CAChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A file within a NAR
type NarFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to FileType:
	//
	//	*NarFile_Regular
	//	*NarFile_Directory
	//	*NarFile_Symlink
	FileType      isNarFile_FileType `protobuf_oneof:"file_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarFile) Reset() {
	*x = NarFile{}
	mi := &file_dnar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarFile) ProtoMessage() {}

func (x *NarFile) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarFile.ProtoReflect.Descriptor instead.
func (*NarFile) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{3}
}

func (x *NarFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NarFile) GetFileType() isNarFile_FileType {
	if x != nil {
		return x.FileType
	}
	return nil
}

func (x *NarFile) GetRegular() *NarFile_RegularFile {
	if x != nil {
		if x, ok := x.FileType.(*NarFile_Regular); ok {
			return x.Regular
		}
	}
	return nil
}

func (x *NarFile) GetDirectory() *NarFile_DirectoryFile {
	if x != nil {
		if x, ok := x.FileType.(*NarFile_Directory); ok {
			return x.Directory
		}
	}
	return nil
}

func (x *NarFile) GetSymlink() *NarFile_SymlinkFile {
	if x != nil {
		if x, ok := x.FileType.(*NarFile_Symlink); ok {
			return x.Symlink
		}
	}
	return nil
}

type isNarFile_FileType interface {
	isNarFile_FileType()
}

type NarFile_Regular struct {
	Regular *NarFile_RegularFile `protobuf:"bytes,2,opt,name=regular,proto3,oneof"`
}

type NarFile_Directory struct {
	Directory *NarFile_DirectoryFile `protobuf:"bytes,3,opt,name=directory,proto3,oneof"`
}

type NarFile_Symlink struct {
	Symlink *NarFile_SymlinkFile `protobuf:"bytes,4,opt,name=symlink,proto3,oneof"`
}

func (*NarFile_Regular) isNarFile_FileType() {}

func (*NarFile_Directory) isNarFile_FileType() {}

func (*NarFile_Symlink) isNarFile_FileType() {}

// Top level file header
type PathTrailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	Files         []*FileDescriptor      `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathTrailer) Reset() {
	*x = PathTrailer{}
	mi := &file_dnar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathTrailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathTrailer) ProtoMessage() {}

func (x *PathTrailer) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathTrailer.ProtoReflect.Descriptor instead.
func (*PathTrailer) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{4}
}

func (x *PathTrailer) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *PathTrailer) GetFiles() []*FileDescriptor {
	if x != nil {
		return x.Files
	}
	return nil
}

// NAR
type NAR struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Core data fields
	Path  string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Files []*NarFile `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	// Narinfo metadata (extracted from local store using nix path-info --json)
	NarHash       string   `protobuf:"bytes,3,opt,name=narHash,proto3" json:"narHash,omitempty"`
	NarSize       uint64   `protobuf:"varint,4,opt,name=narSize,proto3" json:"narSize,omitempty"`
	References    []string `protobuf:"bytes,5,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NAR) Reset() {
	*x = NAR{}
	mi := &file_dnar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NAR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NAR) ProtoMessage() {}

func (x *NAR) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NAR.ProtoReflect.Descriptor instead.
func (*NAR) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{5}
}

func (x *NAR) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NAR) GetFiles() []*NarFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *NAR) GetNarHash() string {
	if x != nil {
		return x.NarHash
	}
	return ""
}

func (x *NAR) GetNarSize() uint64 {
	if x != nil {
		return x.NarSize
	}
	return 0
}

func (x *NAR) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

type NarFile_ChunkDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ChunkType:
	//
	//	*NarFile_ChunkDescriptor_Ca
	//	*NarFile_ChunkDescriptor_Fd
	//	*NarFile_ChunkDescriptor_Inline
	ChunkType     isNarFile_ChunkDescriptor_ChunkType `protobuf_oneof:"chunk_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarFile_ChunkDescriptor) Reset() {
	*x = NarFile_ChunkDescriptor{}
	mi := &file_dnar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarFile_ChunkDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarFile_ChunkDescriptor) ProtoMessage() {}

func (x *NarFile_ChunkDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarFile_ChunkDescriptor.ProtoReflect.Descriptor instead.
func (*NarFile_ChunkDescriptor) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{3, 0}
}

func (x *NarFile_ChunkDescriptor) GetChunkType() isNarFile_ChunkDescriptor_ChunkType {
	if x != nil {
		return x.ChunkType
	}
	return nil
}

func (x *NarFile_ChunkDescriptor) GetCa() *NarFile_ChunkDescriptor_CAChunk {
	if x != nil {
		if x, ok := x.ChunkType.(*NarFile_ChunkDescriptor_Ca); ok {
			return x.Ca
		}
	}
	return nil
}

func (x *NarFile_ChunkDescriptor) GetFd() *NarFile_ChunkDescriptor_FDChunk {
	if x != nil {
		if x, ok := x.ChunkType.(*NarFile_ChunkDescriptor_Fd); ok {
			return x.Fd
		}
	}
	return nil
}

func (x *NarFile_ChunkDescriptor) GetInline() *NarFile_ChunkDescriptor_InlineChunk {
	if x != nil {
		if x, ok := x.ChunkType.(*NarFile_ChunkDescriptor_Inline); ok {
			return x.Inline
		}
	}
	return nil
}

type isNarFile_ChunkDescriptor_ChunkType interface {
	isNarFile_ChunkDescriptor_ChunkType()
}

type NarFile_ChunkDescriptor_Ca struct {
	// Read from CA chunk
	Ca *NarFile_ChunkDescriptor_CAChunk `protobuf:"bytes,1,opt,name=ca,proto3,oneof"`
}

type NarFile_ChunkDescriptor_Fd struct {
	// Read from file descriptor
	Fd *NarFile_ChunkDescriptor_FDChunk `protobuf:"bytes,2,opt,name=fd,proto3,oneof"`
}

type NarFile_ChunkDescriptor_Inline struct {
	// Inline data (for very short data)
	Inline *NarFile_ChunkDescriptor_InlineChunk `protobuf:"bytes,3,opt,name=inline,proto3,oneof"`
}

func (*NarFile_ChunkDescriptor_Ca) isNarFile_ChunkDescriptor_ChunkType() {}

func (*NarFile_ChunkDescriptor_Fd) isNarFile_ChunkDescriptor_ChunkType() {}

func (*NarFile_ChunkDescriptor_Inline) isNarFile_ChunkDescriptor_ChunkType() {}

type NarFile_RegularFile struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Size          uint64                     `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Chunks        []*NarFile_ChunkDescriptor `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Executable    bool                       `protobuf:"varint,3,opt,name=executable,proto3" json:"executable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarFile_RegularFile) Reset() {
	*x = NarFile_RegularFile{}
	mi := &file_dnar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarFile_RegularFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarFile_RegularFile) ProtoMessage() {}

func (x *NarFile_RegularFile) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarFile_RegularFile.ProtoReflect.Descriptor instead.
func (*NarFile_RegularFile) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{3, 1}
}

func (x *NarFile_RegularFile) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *NarFile_RegularFile) GetChunks() []*NarFile_ChunkDescriptor {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *NarFile_RegularFile) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

type NarFile_DirectoryFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executable    bool                   `protobuf:"varint,1,opt,name=executable,proto3" json:"executable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarFile_DirectoryFile) Reset() {
	*x = NarFile_DirectoryFile{}
	mi := &file_dnar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarFile_DirectoryFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarFile_DirectoryFile) ProtoMessage() {}

func (x *NarFile_DirectoryFile) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarFile_DirectoryFile.ProtoReflect.Descriptor instead.
func (*NarFile_DirectoryFile) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{3, 2}
}

func (x *NarFile_DirectoryFile) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

type NarFile_SymlinkFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarFile_SymlinkFile) Reset() {
	*x = NarFile_SymlinkFile{}
	mi := &file_dnar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarFile_SymlinkFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarFile_SymlinkFile) ProtoMessage() {}

func (x *NarFile_SymlinkFile) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarFile_SymlinkFile.ProtoReflect.Descriptor instead.
func (*NarFile_SymlinkFile) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{3, 3}
}

func (x *NarFile_SymlinkFile) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type NarFile_ChunkDescriptor_CAChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // CA chunk index in chunk stream to read from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarFile_ChunkDescriptor_CAChunk) Reset() {
	*x = NarFile_ChunkDescriptor_CAChunk{}
	mi := &file_dnar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarFile_ChunkDescriptor_CAChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarFile_ChunkDescriptor_CAChunk) ProtoMessage() {}

func (x *NarFile_ChunkDescriptor_CAChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarFile_ChunkDescriptor_CAChunk.ProtoReflect.Descriptor instead.
func (*NarFile_ChunkDescriptor_CAChunk) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *NarFile_ChunkDescriptor_CAChunk) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type NarFile_ChunkDescriptor_FDChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // File descriptor index in DnarHeader.files to read from
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Digest        []byte                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"` // Chunk digest (verify that existing store contents match)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarFile_ChunkDescriptor_FDChunk) Reset() {
	*x = NarFile_ChunkDescriptor_FDChunk{}
	mi := &file_dnar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarFile_ChunkDescriptor_FDChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarFile_ChunkDescriptor_FDChunk) ProtoMessage() {}

func (x *NarFile_ChunkDescriptor_FDChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarFile_ChunkDescriptor_FDChunk.ProtoReflect.Descriptor instead.
func (*NarFile_ChunkDescriptor_FDChunk) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{3, 0, 1}
}

func (x *NarFile_ChunkDescriptor_FDChunk) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *NarFile_ChunkDescriptor_FDChunk) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *NarFile_ChunkDescriptor_FDChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *NarFile_ChunkDescriptor_FDChunk) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type NarFile_ChunkDescriptor_InlineChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarFile_ChunkDescriptor_InlineChunk) Reset() {
	*x = NarFile_ChunkDescriptor_InlineChunk{}
	mi := &file_dnar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarFile_ChunkDescriptor_InlineChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarFile_ChunkDescriptor_InlineChunk) ProtoMessage() {}

func (x *NarFile_ChunkDescriptor_InlineChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dnar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarFile_ChunkDescriptor_InlineChunk.ProtoReflect.Descriptor instead.
func (*NarFile_ChunkDescriptor_InlineChunk) Descriptor() ([]byte, []int) {
	return file_dnar_proto_rawDescGZIP(), []int{3, 0, 2}
}

func (x *NarFile_ChunkDescriptor_InlineChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_dnar_proto protoreflect.FileDescriptor

const file_dnar_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"dnar.proto\x12\x04dnar\"&\n" +
	"\fStreamHeader\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x04R\x06length\"C\n" +
	"\x0eFileDescriptor\x12\x1d\n" +
	"\n" +
	"store_path\x18\x01 \x01(\rR\tstorePath\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x1d\n" +
	"\aCAChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xa9\x06\n" +
	"\aNarFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x125\n" +
	"\aregular\x18\x02 \x01(\v2\x19.dnar.NarFile.RegularFileH\x00R\aregular\x12;\n" +
	"\tdirectory\x18\x03 \x01(\v2\x1b.dnar.NarFile.DirectoryFileH\x00R\tdirectory\x125\n" +
	"\asymlink\x18\x04 \x01(\v2\x19.dnar.NarFile.SymlinkFileH\x00R\asymlink\x1a\xff\x02\n" +
	"\x0fChunkDescriptor\x127\n" +
	"\x02ca\x18\x01 \x01(\v2%.dnar.NarFile.ChunkDescriptor.CAChunkH\x00R\x02ca\x127\n" +
	"\x02fd\x18\x02 \x01(\v2%.dnar.NarFile.ChunkDescriptor.FDChunkH\x00R\x02fd\x12C\n" +
	"\x06inline\x18\x03 \x01(\v2).dnar.NarFile.ChunkDescriptor.InlineChunkH\x00R\x06inline\x1a\x1f\n" +
	"\aCAChunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x1ac\n" +
	"\aFDChunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\fR\x06digest\x1a!\n" +
	"\vInlineChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB\f\n" +
	"\n" +
	"chunk_type\x1ax\n" +
	"\vRegularFile\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x125\n" +
	"\x06chunks\x18\x02 \x03(\v2\x1d.dnar.NarFile.ChunkDescriptorR\x06chunks\x12\x1e\n" +
	"\n" +
	"executable\x18\x03 \x01(\bR\n" +
	"executable\x1a/\n" +
	"\rDirectoryFile\x12\x1e\n" +
	"\n" +
	"executable\x18\x01 \x01(\bR\n" +
	"executable\x1a%\n" +
	"\vSymlinkFile\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06targetB\v\n" +
	"\tfile_type\"O\n" +
	"\vPathTrailer\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12*\n" +
	"\x05files\x18\x02 \x03(\v2\x14.dnar.FileDescriptorR\x05files\"\x92\x01\n" +
	"\x03NAR\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\x05files\x18\x02 \x03(\v2\r.dnar.NarFileR\x05files\x12\x18\n" +
	"\anarHash\x18\x03 \x01(\tR\anarHash\x12\x18\n" +
	"\anarSize\x18\x04 \x01(\x04R\anarSize\x12\x1e\n" +
	"\n" +
	"references\x18\x05 \x03(\tR\n" +
	"referencesB%Z#github.com/adisbladis/deltanar/dnarb\x06proto3"

var (
	file_dnar_proto_rawDescOnce sync.Once
	file_dnar_proto_rawDescData []byte
)

func file_dnar_proto_rawDescGZIP() []byte {
	file_dnar_proto_rawDescOnce.Do(func() {
		file_dnar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dnar_proto_rawDesc), len(file_dnar_proto_rawDesc)))
	})
	return file_dnar_proto_rawDescData
}

var file_dnar_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dnar_proto_goTypes = []any{
	(*StreamHeader)(nil),                        // 0: dnar.StreamHeader
	(*FileDescriptor)(nil),                      // 1: dnar.FileDescriptor
	(*CAChunk)(nil),                             // 2: dnar.CAChunk
	(*NarFile)(nil),                             // 3: dnar.NarFile
	(*PathTrailer)(nil),                         // 4: dnar.PathTrailer
	(*NAR)(nil),                                 // 5: dnar.NAR
	(*NarFile_ChunkDescriptor)(nil),             // 6: dnar.NarFile.ChunkDescriptor
	(*NarFile_RegularFile)(nil),                 // 7: dnar.NarFile.RegularFile
	(*NarFile_DirectoryFile)(nil),               // 8: dnar.NarFile.DirectoryFile
	(*NarFile_SymlinkFile)(nil),                 // 9: dnar.NarFile.SymlinkFile
	(*NarFile_ChunkDescriptor_CAChunk)(nil),     // 10: dnar.NarFile.ChunkDescriptor.CAChunk
	(*NarFile_ChunkDescriptor_FDChunk)(nil),     // 11: dnar.NarFile.ChunkDescriptor.FDChunk
	(*NarFile_ChunkDescriptor_InlineChunk)(nil), // 12: dnar.NarFile.ChunkDescriptor.InlineChunk
}
var file_dnar_proto_depIdxs = []int32{
	7,  // 0: dnar.NarFile.regular:type_name -> dnar.NarFile.RegularFile
	8,  // 1: dnar.NarFile.directory:type_name -> dnar.NarFile.DirectoryFile
	9,  // 2: dnar.NarFile.symlink:type_name -> dnar.NarFile.SymlinkFile
	1,  // 3: dnar.PathTrailer.files:type_name -> dnar.FileDescriptor
	3,  // 4: dnar.NAR.files:type_name -> dnar.NarFile
	10, // 5: dnar.NarFile.ChunkDescriptor.ca:type_name -> dnar.NarFile.ChunkDescriptor.CAChunk
	11, // 6: dnar.NarFile.ChunkDescriptor.fd:type_name -> dnar.NarFile.ChunkDescriptor.FDChunk
	12, // 7: dnar.NarFile.ChunkDescriptor.inline:type_name -> dnar.NarFile.ChunkDescriptor.InlineChunk
	6,  // 8: dnar.NarFile.RegularFile.chunks:type_name -> dnar.NarFile.ChunkDescriptor
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_dnar_proto_init() }
func file_dnar_proto_init() {
	if File_dnar_proto != nil {
		return
	}
	file_dnar_proto_msgTypes[3].OneofWrappers = []any{
		(*NarFile_Regular)(nil),
		(*NarFile_Directory)(nil),
		(*NarFile_Symlink)(nil),
	}
	file_dnar_proto_msgTypes[6].OneofWrappers = []any{
		(*NarFile_ChunkDescriptor_Ca)(nil),
		(*NarFile_ChunkDescriptor_Fd)(nil),
		(*NarFile_ChunkDescriptor_Inline)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dnar_proto_rawDesc), len(file_dnar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dnar_proto_goTypes,
		DependencyIndexes: file_dnar_proto_depIdxs,
		MessageInfos:      file_dnar_proto_msgTypes,
	}.Build()
	File_dnar_proto = out.File
	file_dnar_proto_goTypes = nil
	file_dnar_proto_depIdxs = nil
}
